<?php 

$cta_options_url = get_admin_url( null, 'admin.php?page=cta-settings' );

if( function_exists('acf_add_local_field_group') ):

	/* Custom Post Type - Style Settings */
	acf_add_local_field_group(array (
		'key' => 'group_562d96cb75e9b',
		'title' => 'Call To Action',
		'fields' => array (
			array (
				'key' => 'field_562d973e730c4',
				'label' => 'Content',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_562d97df730c5',
				'label' => 'Heading',
				'name' => 'heading',
				'type' => 'text',
				'instructions' => '(optional) Enter a heading to entice your audience to click the call to action button.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_562d9970730c6',
				'label' => 'Sub-heading',
				'name' => 'sub_heading',
				'type' => 'text',
				'instructions' => '(optional) Enter a sub-heading to give the call to action some more context.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_562d9a11730c7',
				'label' => 'Button',
				'name' => 'button_text',
				'type' => 'text',
				'instructions' => '(required) Enter the action text you want to appear in the button.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'Click here!',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_562d9af0730c8',
				'label' => 'Button Link',
				'name' => 'link_type',
				'type' => 'radio',
				'instructions' => 'Choose whether the button should link to an existing page in your site or an off-site URL.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'local' => 'Site page',
					'remote' => 'Off-site URL',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_562d9c22730c9',
				'label' => 'Select a Page',
				'name' => 'select_a_page',
				'type' => 'page_link',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_562d9af0730c8',
							'operator' => '==',
							'value' => 'local',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array (
				),
				'taxonomy' => array (
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_562d9c5b730ca',
				'label' => 'Enter a URL',
				'name' => 'enter_a_url',
				'type' => 'url',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_562d9af0730c8',
							'operator' => '==',
							'value' => 'remote',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array (
				'key' => 'field_562d9cb9730cb',
				'label' => 'Link Target',
				'name' => 'link_target',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_562d9af0730c8',
							'operator' => '==',
							'value' => 'remote',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Open URL in a new tab/window',
				'default_value' => 1,
			),
			array (
				'key' => 'field_562d9d49730cc',
				'label' => 'Style',
				'name' => 'style',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array (
				'key' => 'field_562d9e8b730cd',
				'label' => 'Override Your Settings',
				'name' => 'override_your_settings',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'You can use these fields to override the default style preferences you have assigned on the <a href="'.$cta_options_url.'">CTA Settings</a> page.',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array (
				'key' => 'field_562d9f90730ce',
				'label' => 'Background',
				'name' => 'background_color',
				'type' => 'color_picker',
				'instructions' => 'Choose a background color for the Call to Action module.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
			array (
				'key' => 'field_562d9fd2730cf',
				'label' => 'Text',
				'name' => 'text_color',
				'type' => 'color_picker',
				'instructions' => 'Choose a color for the heading/sub-heading text.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
			array (
				'key' => 'field_562da035730d0',
				'label' => 'Button',
				'name' => 'button_color',
				'type' => 'color_picker',
				'instructions' => 'Choose a background color for the button (Note: make sure the button stands out from the background color).',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
			array (
				'key' => 'field_562da117730d1',
				'label' => 'Button Text',
				'name' => 'button_text_color',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'light' => 'Light',
					'dark' => 'Dark',
				),
				'default_value' => array (
				),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 1,
				'ajax' => 0,
				'placeholder' => '',
				'disabled' => 0,
				'readonly' => 0,
			),
			array (
				'key' => 'field_562da1d0730d2',
				'label' => 'Button Size',
				'name' => 'button_size',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'normal' => 'Normal',
					'large' => 'Large',
					'xlarge' => 'X-Large',
				),
				'default_value' => array (
				),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 1,
				'ajax' => 0,
				'placeholder' => '',
				'disabled' => 0,
				'readonly' => 0,
			),
			array (
				'key' => 'field_562da26e730d3',
				'label' => 'Button Corners',
				'name' => 'button_corners',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'round' => 'Rounded',
					'square' => 'Square',
				),
				'default_value' => array (
				),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 1,
				'ajax' => 0,
				'placeholder' => '',
				'disabled' => 0,
				'readonly' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'bugle_call_to_action',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'seamless',
		'label_placement' => 'left',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	/* Options Page - Default CTA Settings */
	acf_add_local_field_group(array (
		'key' => 'group_56e1ed2e9e17e',
		'title' => 'Default CTA',
		'fields' => array (
			array (
				'key' => 'field_56e1ed3a8175f',
				'label' => 'Choose a default CTA module...',
				'name' => 'default_cta_mod',
				'type' => 'post_object',
				'instructions' => 'Choose a default Call To Action module to display on all pages on your site.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array (
					0 => 'bugle_call_to_action',
				),
				'taxonomy' => array (
				),
				'allow_null' => 0,
				'multiple' => 0,
				'return_format' => 'object',
				'ui' => 1,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'cta-settings',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	/* Options Page - Style Settings */
	acf_add_local_field_group(array (
		'key' => 'group_562da2f2b0189',
		'title' => 'CTA Settings',
		'fields' => array (
			array (
				'key' => 'field_562da76bdda68',
				'label' => 'Default Styles',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Pick colors that match your theme but also stand out enough to catch the eye of your audience.
	You can choose to override these style settings on a case-by-case basis each time you create a new Call to Action module.',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array (
				'key' => 'field_562da2f2bc890',
				'label' => 'Background',
				'name' => 'background_color',
				'type' => 'color_picker',
				'instructions' => 'Choose a background color for the Call to Action module.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#f2f2f2',
			),
			array (
				'key' => 'field_562da2f2bda37',
				'label' => 'Text',
				'name' => 'text_color',
				'type' => 'color_picker',
				'instructions' => 'Choose a color for the heading/sub-heading text.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#121212',
			),
			array (
				'key' => 'field_562da2f2be00b',
				'label' => 'Button',
				'name' => 'button_color',
				'type' => 'color_picker',
				'instructions' => 'Choose a background color for the button (Note: make sure the button stands out from the background color).',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#FB8A27',
			),
			array (
				'key' => 'field_562da2f2be9fe',
				'label' => 'Button Text',
				'name' => 'button_text_color',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'light' => 'Light',
					'dark' => 'Dark',
				),
				'default_value' => array (
					'light' => 'light',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
				'disabled' => 0,
				'readonly' => 0,
			),
			array (
				'key' => 'field_562da2f2bf7f9',
				'label' => 'Button Size',
				'name' => 'button_size',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'normal' => 'Normal',
					'large' => 'Large',
					'xlarge' => 'X-Large',
				),
				'default_value' => array (
					'large' => 'large',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
				'disabled' => 0,
				'readonly' => 0,
			),
			array (
				'key' => 'field_562da2f2bfe6c',
				'label' => 'Button Corners',
				'name' => 'button_corners',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'round' => 'Rounded',
					'square' => 'Square',
				),
				'default_value' => array (
					'round' => 'round',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
				'disabled' => 0,
				'readonly' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'cta-settings',
				),
			),
		),
		'menu_order' => 1,
		'position' => 'acf_after_title',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

endif;

/* eof */